---
  primary:
    address: ":6000"
  health:
    address: ":6001"
    options:
      - "PayloadsOverZero"
      - "PayloadsOverHundred"
      - "PayloadsOverThousand"
      - "PayloadsOverTenThousand"
  pprof:
    address: ":6002"
  metric:
    address: ":6003"
    metricsOptions:
      namespace: "xmidt"
      subsystem: "caduceus"
  log:
    file: "stdout"
    level: "DEBUG"
    json: true
  env: test
  fqdn: caduceus
  scheme: http

  numWorkerThreads: 10
  jobQueueSize: 10
  sender:
    numWorkersPerSender: 5000
    queueSizePerSender: 100000
    cutOffPeriod: 10s
    linger: 180s
    clientTimeout: 60s
    deliveryRetries: 1
    deliveryInterval: 10ms
    responseHeaderTimeout: 10s
  profilerFrequency: 15
  profilerDuration: 15
  profilerQueueSize: 100
  totalIncomingPayloadSizeBuckets:
    - 100
    - 1000
    - 10000
  perSourceIncomingPayloadSizeBuckets:
    - 100
    - 1000
    - 10000

  authHeader: ["dXNlcjpwYXNz"]

  webhook:
    argus:
      bucket: webhooks
      address: http://argus:6600
      pullInterval: 5s
      adminToken: Hzu1WpIe7S8G
      auth:
        Basic: Basic dXNlcjpwYXNz
        